### PR TITLE
[ finishes #160105935]Landing Page Complete

### PR DESCRIPTION
**Pull request by EmmanuelBeja**
What does this PR do?
Creates the Landing Page with login form

Description of Task to be completed?
Tasks completed:
-Login

How should this be manually tested?

git clone

https://github.com/EmmanuelBeja/Fast-Food-Fast.git

cd Fast-Food-Fast
cd UI
open index.html in your browser

What are the relevant pivotal tracker stories?
#160105935

Screenshot

screenshot from 2018-08-30 17-35-27

### CODE REVIEW

**Comment by danielotieno** [comment]
Awesome

**Comment by kamaudan** [comment]
That looks  good.

**Comment by iddle254** [comment]
wuuuueh..still stuck on the ryme "good mood food"Big up yourself.This is good

**Comment by EmmanuelBeja** [comment]
thank you @danielotieno @SilasKenneth @kamaudan @iddle254

**Pull request closed without merging**
