### PR TITLE
[finishes #160106500] User Home Page

### PR DESCRIPTION
**Pull request by EmmanuelBeja**
What does this PR do?
Creates the User Home Page to view Food Items

Description of Task to be completed?
Tasks completed:
-A user should be able to order for food

How should this be manually tested?

git clone

https://github.com/EmmanuelBeja/Fast-Food-Fast.git

cd Fast-Food-Fast
cd UI
open user.html in your browser

What are the relevant pivotal tracker stories?
#160106500

Screenshot
screenshot from 2018-08-30 22-52-01

### CODE REVIEW

**Comment by PromasterGuru** [comment]
Awesome :100:

**Comment by Mik3y-F** [comment]
Looks awesome 👍

**Comment by kamaudan** [comment]
Superb.

**Comment by ClintPy** [comment]
Wooow great work

**Pull request closed without merging**
